name: generae Ascii Artwork
on: push 

jobs:
  build_job1: 
    runs-on: ubuntu-latest

    steps:
      -  name: install cowsay Program
         run: sudo apt-get install cowsay -y 
      -  name: Execute cowsay cmd 
         run: cowsay -f dragon "Run for cover, Iam a Dragon" >> dragon.txt
      -  uses: actions/upload-artifact@v4
         with: 
          name: dragon-artifact
          path: dragon.txt 
  test_job: 
     runs-on: ubuntu-latest
     needs: build_job1
     steps: 
       - uses: actions/download-artifact@v4
         with: 
          name: dragon-artifact

       - name: Test file Exists
         run: grep -i "dragon" dragon.txt

  deploy_job: 
      runs-on: ubuntu-lates
      needs: test_job
      steps: 
        - uses: actions/download-artifact@v4
          with: 
            name: dragon-artifact
        - name: Read file 
          run: cat dragon.txt
