name: generate acii art work
on: push 

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps: 
        -  name: checkout 
           uses: actions/checkout@v4 
        -  name: execute shell script
           run: ./ascii-script.sh
       
